twitter:
  consumer_key: "78Xe54R18Dx0xjehhGOAw"
  secret_key: "IMNaQoy65nLkWa15qp5HvoqHYAu5XTXCfgg86fKC0"

facebook:
  consumer_key: "542283809165927"
  secret_key: "1a8e252855790961ed937a993304e480"

tumblr:
  consumer_key: "RTeUQFDPqbrtYPZMgpEkDPxkMAOudz2bJOgo9Mb0Fo2cgf6Mex"
  secret_key: "yc022iFsUezIMjXYsiRffv1pEhX2hsHB0FW2LK4hmLzgmTeYxl"

linkedin:
  consumer_key: "l6on5uqdtfc8"
  secret_key: "LiDHc2gdkyYTOEuB"

vkontakte:
  consumer_key: "3756304"
  secret_key: "PQlol0o4iIEn7GEljq49"
