twitter:
  app_key: "78Xe54R18Dx0xjehhGOAw"
  app_secret: "IMNaQoy65nLkWa15qp5HvoqHYAu5XTXCfgg86fKC0"

facebook:
  app_key: "542283809165927"
  app_secret: "1a8e252855790961ed937a993304e480"

linkedin:
  app_key: "l6on5uqdtfc8"
  app_secret: "LiDHc2gdkyYTOEuB"

vkontakte:
  app_key: "3756304"
  app_secret: "PQlol0o4iIEn7GEljq49"
